services:
  app:
    image: steamry-app:1.0.0
    container_name: steamry-app
    build:
      context: .
      args:
        PORT: ${PORT}
    env_file: .env
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    networks:
      - coolify

  db:
    image: postgres:17
    container_name: steamry-db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - steamry-db:/var/lib/postgresql
    profiles:
      - local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  coolify:
    external: true

volumes:
  steamry-db:
    driver: local
